### ISSUE TITLE
Message after menu

### ISSUE THREAD

**Issue by ThatOneCalculator** [LiBa001/disputils#10]
When I send a menu, messages that should be sent after the menu is sent only appear once the menu is inactive. Is it possible to have messages below the menu while it's still active?

```python
await helppaginator.run()
staticembedmessage = await ctx.send(embed=staticembed)
await ctx.send("Don't forget to check out `;premium`!")
```

The last 2 only send after the menu is over.

**Comment by LiBa001** [comment]
The `await` in `await helppaginator.run()` makes sure that the program waits for the paginator to finish, before continuing execution. If you do not want to wait at that point, you should probably execute the paginator as an asyncio task:
```Python
paginator_task = asyncio.ensure_future(helppaginator.run())  # schedule paginator in the background
. . .  # do your other stuff
await paginator_task  # finally, wait for the paginator to finish
```
