### ISSUE TITLE
Embed Fields

### ISSUE THREAD

**Issue by AndrewNunnes** [LiBa001/disputils#14]
How are we supposed to add our embed fields with this?

**Comment by LiBa001** [comment]
What exactly do you wanna know? How to add embed fields to the paginator pages? You can just use the `discord.Embed` objects as you do usually (i.e. using the `.add_field(…)` method). Please try to further explain your problem, if this answer doesn't already solve it.

**Comment by LiBa001** [comment]
maybe this is related? #9
