### ISSUE TITLE
Confusing introduction

### ISSUE THREAD

**Issue by sh0tx420** [LiBa001/disputils#17]
I'm doing exactly as the picture in README.md shows and this happens
![fuck1](https://user-images.githubusercontent.com/55631215/95095475-c3860980-0733-11eb-8085-e3fb1753b877.png)
![fuck2](https://user-images.githubusercontent.com/55631215/95095479-c4b73680-0733-11eb-941a-58ac399d339b.png)

**Comment by LilJess13** [comment]
You need to import Embed from the discord module to use it like that. 
So "from discord import Embed"

**Comment by sh0tx420** [comment]
Doesn't `import discord` do that already?

**Comment by LilJess13** [comment]
`import discord` imports the entire discord module. You can still get embeds with discord.Embed though.
doing `from discord import Embed` imports the class directly and lets you drop the `discord.`

**Comment by sh0tx420** [comment]
ok
