### ISSUE TITLE
BotConfirmation Appears to Not Work

### ISSUE THREAD

**Issue by ferociouskyle** [LiBa001/disputils#22]
Hello! This is my first time opening an issue, so sorry if I do it incorrectly. 

I was using the disputils in my bot and I just noticed that confirms/decline's are not working. I made sure it wasn't my code by creating a new command (just like in the docs) and the same thing happens. I click on the reaction, then a blank embed is posted. 

[[Screenshot](https://gyazo.com/4bc2634fabb217ac3a3833e63b5bde7a)]

I am using:
Python 3.8
discord.py 1.5.1

**Comment by ferociouskyle** [comment]
I did just test on an older version of discord.py and it seems to be working on there. Perhaps there was something in 1.5.1 that broke confirmations?

**Comment by LiBa001** [comment]
That seems very weird. Can you please also post the code that causes this behavior, since I never had something like this happening with `BotConfirmation`.

**Comment by LiBa001** [comment]
Closing this now, since you didn't respond. Feel free to reopen providing the requested code if the bug still persists.
