### ISSUE TITLE
[request] paginator with only left and right buttons

### ISSUE THREAD

**Issue by theothersophie** [LiBa001/disputils#31]
Would it be straightforward to make a version of the paginator that only adds left and right options? I find that the start, end, stop buttons are often quite unnecessary.

**Comment by LiBa001** [comment]
I can definitely look into ways of making the controls more customizable and how easy or hard something like this might be to implement. I could imagine something like:
 1. passing a `control_emojis` tuple where you can set `None` in place of the emojis that you want to omit
 2. passing `control_emojis` tuple with different lengths and use the length to determine what they control (i.e. length 3 -> left, right, stop)
 3. passing an extra argument, like an enum, to explicitly set the controls

I'll need to further look into it and try some things in the code later. Thanks for your suggestion!
