### ISSUE TITLE
[FEATURE REQUEST] Cleanup setting

### ISSUE THREAD

**Issue by tylovejoy** [LiBa001/disputils#37]
It would be useful for a "clean up" setting which would automatically delete the embed on timeout. Like as soon as the reactions would disappear, just delete the entire message.

**Comment by LiBa001** [comment]
You can basically do that by calling the `quit` method, so I'm not sure if it's really necessary.
Also, could you specify whether you mean this for a specific class class (e.g. `EmbedPaginator`, …) or in general?

**Comment by tylovejoy** [comment]
Oh, the `quit` method works quite nicely. I wasn't aware.
I was wanting this for `EmbedPaginator` in particular.

**Comment by LiBa001** [comment]
Well, if the `quit` methods works for you, I'll just close this issue for now ^^
