### ISSUE TITLE
how to make it send a message to the author DM

### ISSUE THREAD

**Issue by vichubenzene** [LiBa001/disputils#39]
it works fine in same channel... but what should I change to make it send a  DM

@client.command()
async def paginate(ctx):
    embeds = [
        discord.Embed(title="test page 1", description="This is just some test content!", color=0x115599),
        discord.Embed(title="test page 2", description="Nothing interesting here.", color=0x5599ff),
        discord.Embed(title="test page 3", description="Why are you still here?", color=0x191638)
    ]
    paginator = BotEmbedPaginator(ctx.author, embeds)
    await paginator.run()

**Comment by LiBa001** [comment]
You can specify a channel in `paginator.run(channel=...)`.
You should be able to just use `ctx.author` as the channel for sending a DM.

docs: https://disputils.readthedocs.io/en/latest/reference.html#disputils.EmbedPaginator.run
