### ISSUE TITLE
How to add fields to the embed?

### ISSUE THREAD

**Issue by BubbletopTag** [LiBa001/disputils#5]
I was wondering how to add fields to the embed pages.

**Comment by LiBa001** [comment]
This is probably not relevant anymore, but the embed pages are just normal [discord.py embeds](https://discordpy.readthedocs.io/en/latest/api.html#discord.Embed) and you can add fields like this: https://discordpy.readthedocs.io/en/latest/api.html#discord.Embed.add_field
